##################################################################
#
# docker-compose.yml
#
# author: Rion Dooley <dooley@tacc.utexas.edu>
#
# This is the base file to start the lightning viz server
# in development mode. It will run on your docker host, port 3000.
# To add authentication to the server, or leverage S3 storage,
# fill in the environment variables with the appropraite values.
#
###################################################################
web:
  extends:
    file: common.yml
    service: web
  environment:
    NODE_ENV: development
    LIGHTNING_URL:
    LIGHTNING_USERNAME:
    LIGHTNING_PASSWORD:
    S3_KEY:
    S3_BUCKET:
    S3_SECRET: